<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>NutHub.Services</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NutHub.Core\NutHub.Core.csproj" />
    <PackageReference Include="MailKit" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="NutHub.Services.Tests" />
  </ItemGroup>
</Project>
