<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>NutHub.Drivers.Net</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NutHub.Core\NutHub.Core.csproj" />

  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="NutHub.Drivers.Net.Tests" />
  </ItemGroup>
</Project>
