<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>NutHub.Storage</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\NutHub.Core\NutHub.Core.csproj" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="NutHub.Storage.Tests" />
  </ItemGroup>
</Project>
