// Mapping tables ported from Network UPS Tools, drivers/ever-hid.c (Ever HID 0.11),
// GPL-2.0-or-later. Keep them in sync with that file rather than editing entries by hand.
using NutHub.Drivers.Hid.Descriptors;
using static NutHub.Drivers.Hid.UsbHid.HidMapFlags;

namespace NutHub.Drivers.Hid.UsbHid.Subdrivers;

internal sealed partial class EverSubdriver
{
    /// <summary>The NUT subdriver this one is ported from, reported as driver.version.data.</summary>
    public override string Version => "Ever HID 0.11";

    /// <summary>Vendor-specific usage names (NUT ever_usage_lkp).</summary>
    private static readonly HidUsageTable VendorUsageTable = new(
    [
        ("EVER1", 0x00000000),
        ("EVER2", 0xff000000),
        ("EVER3", 0xff000001),
        ("EVER4", 0xff000002),
        ("EVER5", 0xff000003),
        ("EVER6", 0xff000004),
        ("EVER7", 0xff000005),
        ("EVER8", 0xff000006),
        ("EVER9", 0xff000007),
        ("EVER10", 0xff000008),
        ("EVER11", 0xff000009),
        ("EVER12", 0xff000010),
        ("EVER13", 0xff000011),
        ("EVER14", 0xff000012),
        ("EVER15", 0xff000013),
        ("EVER16", 0xff000014),
        ("EVER17", 0xff000015),
        ("EVER18", 0xff000016),
        ("EVER19", 0xff000017),
        ("EVER20", 0xff000018),
        ("EVER21", 0xff000019),
        ("EVER22", 0xff00001a),
        ("EVER23", 0xff00001b),
        ("EVER24", 0xff00001c),
        ("EVER25", 0xff00001d),
        ("EVER26", 0xff00001e),
        ("EVER27", 0xff00001f),
        ("EVER28", 0xff000020),
        ("EVER29", 0xff000021),
        ("EVER30", 0xff000022),
        ("EVER31", 0xff000023),
        ("EVER32", 0xff000030),
        ("EVER33", 0xff000031),
        ("EVER34", 0xff000032),
        ("EVER35", 0xff000033),
        ("EVER36", 0xff000034),
        ("EVER37", 0xff000035),
        ("EVER38", 0xff000036),
        ("EVER39", 0xff000037),
        ("EVER40", 0xff000038),
        ("EVER41", 0xff000039),
        ("EVER42", 0xff000040),
        ("EVER43", 0xff000041),
        ("EVER44", 0xff000042),
        ("EVER45", 0xff000043),
        ("EVER46", 0xff000044),
        ("EVER47", 0xff000045),
        ("EVER48", 0xff000046),
        ("EVER49", 0xff000050),
        ("EVER50", 0xff000051),
        ("EVER51", 0xff000052),
        ("EVER52", 0xff000053),
        ("EVER53", 0xff000054),
        ("EVER54", 0xff000060),
        ("EVER55", 0xff000061),
        ("EVER56", 0xff000062),
        ("EVER57", 0xff000063),
        ("EVER58", 0xff000064),
        ("EVER59", 0xff000066),
        ("EVER60", 0xff000067),
        ("EVER61", 0xff000068),
        ("EVER62", 0xff000069),
        ("EVER63", 0xff00006a),
        ("EVER64", 0xff00006b),
        ("EVER65", 0xff00006c),
        ("EVER66", 0xff00006d),
        ("EVER67", 0xff00006e),
        ("EVER68", 0xff00006f),
        ("EVER69", 0xff000070),
        ("EVER70", 0xff000071),
        ("EVER71", 0xff000072),
        ("EVER72", 0xff000073),
        ("EVER73", 0xff000074),
        ("EVER74", 0xff000075),
        ("EVER75", 0xff000076),
        ("EVER76", 0xff000077),
        ("EVER77", 0xff000078),
        ("EVER78", 0xff000079),
        ("EVER79", 0xff00007a),
        ("EVER80", 0xff00007b),
        ("EVER81", 0xff00007c),
        ("EVER82", 0xff00007d),
        ("EVER83", 0xff00007e),
        ("EVER84", 0xff00007f),
        ("EVER85", 0xff000080),
        ("EVER86", 0xff000081),
        ("EVER87", 0xff000082),
        ("EVER88", 0xff000083),
        ("EVER89", 0xff000084),
        ("EVER90", 0xff000085),
        ("EVER91", 0xff000086),
        ("EVER92", 0xff000087),
        ("EVER93", 0xff000088),
        ("EVER94", 0xff000089),
        ("EVER95", 0xff00008a),
        ("EVER96", 0xff00008b),
        ("EVER97", 0xff000090),
        ("EVER98", 0xff000091),
        ("EVER99", 0xff000092),
        ("EVER100", 0xff000093),
        ("EVER101", 0xff000094),
        ("EVER102", 0xff000095),
        ("EVER103", 0xff000096),
        ("EVER104", 0xff000097),
    ]);

    /// <summary>The USB ids this subdriver supports (NUT ever_usb_device_table).</summary>
    private static readonly UsbDeviceId[] DeviceIds =
    [
        new(0x0483, 0xa113),
        new(0x2e51, 0xffff),
        new(0x2e51, 0x0000),
    ];

    /// <summary>Builds the HID to NUT mapping table; function lookups bind to this instance's state.</summary>
    private HidMapping[] BuildMappings()
    {
        NutLookup everAlarms = NutLookup.Create([], EverAlarmsFun, null);
        NutLookup everFormatHardware = NutLookup.Create([], EverFormatHardwareFun, null);
        NutLookup everFormatVersion = NutLookup.Create([], EverFormatVersionFun, null);
        NutLookup everIpAddress = NutLookup.Create([], EverIpAddressFun, null);
        NutLookup everMacAddress = NutLookup.Create([], EverMacAddressFun, null);
        NutLookup everMessages = NutLookup.Create([], EverMessagesFun, null);
        NutLookup everOnOffInfo = NutLookup.Create([], EverOnOffFun, null);
        NutLookup everPackets = NutLookup.Create([], EverPacketsFun, null);
        NutLookup everWorkmode = NutLookup.Create([], EverWorkmodeFun, null);

        return
        [
            new("experimental.battery.batteryid", 0, "UPS.BatterySystem.Battery.BatteryID", "%.0f", None, null),
            new("experimental.battery.systemid", 0, "UPS.BatterySystem.BatterySystemID", "%.0f", None, null),
            new("experimental.battery.chargerid", 0, "UPS.BatterySystem.Charger.ChargerID", "%.0f", None, null),
            new("experimental.battery.input_flowid", 0, "UPS.BatterySystem.Input.FlowID", "%.0f", None, null),
            new("experimental.battery.input_id", 0, "UPS.BatterySystem.Input.InputID", "%.0f", None, null),
            new("experimental.battery.output_flowid", 0, "UPS.BatterySystem.Output.FlowID", "%.0f", None, null),
            new("experimental.battery.output_id", 0, "UPS.BatterySystem.Output.OutputID", "%.0f", None, null),
            new("experimental.id.firmware_version_inverter", 0, "UPS.EVER1.EVER13", "%s", None, everFormatVersion),
            new("experimental.id.firmware_version_interfaces", 0, "UPS.EVER1.EVER14", "%s", None, everFormatVersion),
            new("experimental.id.hardware_version", 0, "UPS.EVER1.EVER15", "%s", None, everFormatHardware),
            new("experimental.id.protocol_version_inverter", 0, "UPS.EVER1.EVER16", "%s", None, everFormatVersion),
            new("experimental.id.protocol_version_interfaces", 0, "UPS.EVER1.EVER17", "%s", None, everFormatVersion),
            new("ups.temperature", 0, "UPS.EVER1.EVER42", "%s", None, CommonLookups.KelvinCelsiusConversion),
            new("battery.temperature", 0, "UPS.EVER1.EVER43", "%s", None, CommonLookups.KelvinCelsiusConversion),
            new("output.powerfactor", 0, "UPS.EVER1.EVER44", "%.0f", None, null),
            new("experimental.control.ups_on", 0, "UPS.EVER1.EVER45.EVER46", "%.0f", Rw | Num, null),
            new("experimental.control.clear_fault", 0, "UPS.EVER1.EVER45.EVER47", "%.0f", Rw | Num, null),
            new("experimental.control.clear_battery_fault", 0, "UPS.EVER1.EVER45.EVER48", "%.0f", Rw | Num, null),
            new("experimental.control.epo_blocked", 0, "UPS.EVER1.EVER49.EVER50", "%.0f", Rw | Num, null),
            new("experimental.control.green_mode", 0, "UPS.EVER1.EVER49.EVER51", "%.0f", Rw | Num, null),
            new("experimental.control.button_sound", 0, "UPS.EVER1.EVER49.EVER52", "%.0f", Rw | Num, null),
            new("experimental.control.audible_alarm", 0, "UPS.EVER1.EVER49.EVER53", "%.0f", Rw | Num, null),
            new("output.voltage", 3, "UPS.EVER1.EVER54", "%.0f", Rw | Str, null),
            new("experimental.config.overload_clearance_threshold", 2, "UPS.EVER1.EVER59", "%.0f", Rw | Str, null),
            new("experimental.config.stb_charge", 2, "UPS.EVER1.EVER60", "%.0f", Rw | Str, null),
            new("battery.packs.external", 1, "UPS.EVER1.EVER61", "%.0f", Rw | Str, null),
            new("experimental.statistics.mains_loss_counter", 0, "UPS.EVER1.EVER62", "%.0f", None, null),
            new("experimental.statistics.lowering_AVR_trigger_counter", 0, "UPS.EVER1.EVER63", "%.0f", None, null),
            new("experimental.statistics.rising_AVR_trigger_counter", 0, "UPS.EVER1.EVER64", "%.0f", None, null),
            new("experimental.statistics.overload_counter", 0, "UPS.EVER1.EVER65", "%.0f", None, null),
            new("experimental.statistics.short_circuit_counter", 0, "UPS.EVER1.EVER66", "%.0f", None, null),
            new("experimental.statistics.discharge_counter", 0, "UPS.EVER1.EVER67", "%.0f", None, null),
            new("experimental.statistics.overheat_counter", 0, "UPS.EVER1.EVER68", "%.0f", None, null),
            new("experimental.statistics.mains_operation_time", 0, "UPS.EVER1.EVER69", "%.0f", None, null),
            new("experimental.statistics.autonomous_operation_time", 0, "UPS.EVER1.EVER70", "%.0f", None, null),
            new("experimental.statistics.overload_operation_time", 0, "UPS.EVER1.EVER71", "%.0f", None, null),
            new("experimental.networkcard.mac_address", 0, "UPS.EVER1.EVER72", "%s", None, everMacAddress),
            new("experimental.networkcard.notification_destination_ip", 0, "UPS.EVER1.EVER73", "%s", None, everIpAddress),
            new("experimental.networkcard.send_packets", 0, "UPS.EVER1.EVER77", "%s", None, everPackets),
            new("experimental.networkcard.received_packets", 0, "UPS.EVER1.EVER78", "%s", None, everPackets),
            new("experimental.networkcard.send_packets_err", 0, "UPS.EVER1.EVER79", "%s", None, everPackets),
            new("experimental.networkcard.received_packets_err", 0, "UPS.EVER1.EVER80", "%s", None, everPackets),
            new("experimental.networkcard.config_dhcp_enabled", 0, "UPS.EVER1.EVER85.EVER86", "%.0f", None, null),
            new("experimental.networkcard.config_ethernet_enabled", 0, "UPS.EVER1.EVER85.EVER87", "%.0f", None, null),
            new("experimental.networkcard.config_http_enabled", 0, "UPS.EVER1.EVER85.EVER88", "%.0f", None, null),
            new("experimental.networkcard.config_snmp_enabled", 0, "UPS.EVER1.EVER85.EVER89", "%.0f", None, null),
            new("experimental.networkcard.config_snmp_trap_enabled", 0, "UPS.EVER1.EVER85.EVER90", "%.0f", None, null),
            new("experimental.networkcard.config_readonly", 0, "UPS.EVER1.EVER85.EVER91", "%.0f", None, null),
            new("experimental.networkcard.config_restart_eth", 0, "UPS.EVER1.EVER85.EVER96", "%.0f", None, null),
            new("experimental.networkcard.ip_address", 0, "UPS.EVER1.EVER93", "%s", None, everIpAddress),
            new("experimental.networkcard.network_mask", 0, "UPS.EVER1.EVER94", "%s", None, everIpAddress),
            new("experimental.networkcard.default_gateway", 0, "UPS.EVER1.EVER95", "%s", None, everIpAddress),
            new("ups.realpower.nominal", 0, "UPS.Flow.ConfigActivePower", "%.0f", None, null),
            new("ups.power.nominal", 0, "UPS.Flow.ConfigApparentPower", "%.0f", None, null),
            new("output.frequency.nominal", 0, "UPS.Flow.ConfigFrequency", "%.0f", None, null),
            new("output.voltage.nominal", 0, "UPS.Flow.ConfigVoltage", "%.0f", None, null),
            new("experimental.ups.flow_id", 0, "UPS.Flow.FlowID", "%.0f", None, null),
            new("outlet.1.id", 0, "UPS.OutletSystem.Outlet.OutletID", "%.0f", None, null),
            new("experimental.outlet.1.present", 0, "UPS.OutletSystem.Outlet.PresentStatus.Present", "%.0f", None, CommonLookups.YesNoInfo),
            new("outlet.1.switchable", 0, "UPS.OutletSystem.Outlet.PresentStatus.Switchable", "%.0f", None, CommonLookups.YesNoInfo),
            new("outlet.1.status", 0, "UPS.OutletSystem.Outlet.PresentStatus.SwitchOn/Off", "%.0f", None, null),
            new("experimental.outlet.1.undefined", 0, "UPS.OutletSystem.Outlet.PresentStatus.Undefined", "%.0f", None, null),
            new("experimental.outlet.1.system_id", 0, "UPS.OutletSystem.OutletSystemID", "%.0f", None, null),
            new("experimental.outlet.1.switch_off_control", 0, "UPS.OutletSystem.Outlet.SwitchOffControl", "%.0f", Rw | Num, null),
            new("experimental.outlet.1.switch_on_control", 0, "UPS.OutletSystem.Outlet.SwitchOnControl", "%.0f", Rw | Num, null),
            new("experimental.powerconverter.input_flow_id", 0, "UPS.PowerConverter.Input.FlowID", "%.0f", None, null),
            new("input.frequency", 0, "UPS.PowerConverter.Input.Frequency", "%.0f", None, null),
            new("experimental.powerconverter.input_id", 0, "UPS.PowerConverter.Input.InputID", "%.0f", None, null),
            new("input.voltage", 0, "UPS.PowerConverter.Input.Voltage", "%.0f", None, null),
            new("ups.realpower", 0, "UPS.PowerConverter.Output.ActivePower", "%.0f", None, null),
            new("ups.power", 0, "UPS.PowerConverter.Output.ApparentPower", "%.0f", None, null),
            new("output.current", 0, "UPS.PowerConverter.Output.Current", "%.0f", None, null),
            new("experimental.powerconverter.output_flowid", 0, "UPS.PowerConverter.Output.FlowID", "%.0f", None, null),
            new("output.frequency", 0, "UPS.PowerConverter.Output.Frequency", "%.0f", None, null),
            new("experimental.powerconverter.output_id", 0, "UPS.PowerConverter.Output.OutputID", "%.0f", None, null),
            new("ups.load", 0, "UPS.PowerConverter.Output.PercentLoad", "%.0f", None, null),
            new("output.voltage", 0, "UPS.PowerConverter.Output.Voltage", "%.0f", None, null),
            new("experimental.powerconverter.powerconverterid", 0, "UPS.PowerConverter.PowerConverterID", "%.0f", None, null),
            new("experimental.powersummary.capacity_granularity_1", 0, "UPS.PowerSummary.CapacityGranularity1", "%.0f", None, null),
            new("experimental.powersummary.capacity_granularity_2", 0, "UPS.PowerSummary.CapacityGranularity2", "%.0f", None, null),
            new("experimental.powersummary.capacity_mode", 0, "UPS.PowerSummary.CapacityMode", "%.0f", None, null),
            new("ups.delay.shutdown", 10, "UPS.PowerSummary.DelayBeforeShutdown", "20", Rw | Str | Absent, null),
            new("battery.capacity", 0, "UPS.PowerSummary.DesignCapacity", "%.0f", None, null),
            new("experimental.powersummary.flow_id", 0, "UPS.PowerSummary.FlowID", "%.0f", None, null),
            new("battery.capacity", 0, "UPS.PowerSummary.FullChargeCapacity", "%.0f", None, null),
            new("battery.type", 0, "UPS.PowerSummary.iDeviceChemistry", "%.0f", None, null),
            new("ups.load", 0, "UPS.PowerSummary.PercentLoad", "%.0f", None, null),
            new("experimental.powersummary.rechargeable", 0, "UPS.PowerSummary.Rechargeable", "%.0f", None, null),
            new("battery.charge", 0, "UPS.PowerSummary.RemainingCapacity", "%.0f", None, null),
            new("battery.runtime.low", 0, "UPS.PowerSummary.RemainingTimeLimit", "%.0f", Rw | Num, null),
            new("battery.runtime", 0, "UPS.PowerSummary.RunTimeToEmpty", "%.0f", None, null),
            new("battery.voltage", 0, "UPS.PowerSummary.Voltage", "%.0f", None, null),
            new("ups.timer.shutdown", 0, "UPS.PowerSummary.DelayBeforeShutdown", "%.0f", QuickPoll, null),
            new("BOOL", 0, "UPS.PowerSummary.PresentStatus.ACPresent", null, QuickPoll, CommonLookups.OnlineInfo),
            new("BOOL", 0, "UPS.PowerSummary.PresentStatus.AwaitingPower", null, QuickPoll, CommonLookups.AwaitingpowerInfo),
            new("BOOL", 0, "UPS.PowerSummary.PresentStatus.BatteryPresent", null, None, CommonLookups.NobatteryInfo),
            new("BOOL", 0, "UPS.PowerSummary.PresentStatus.CommunicationLost", null, None, CommonLookups.CommfaultInfo),
            new("BOOL", 0, "UPS.PowerSummary.PresentStatus.Discharging", null, QuickPoll, CommonLookups.DischargingInfo),
            new("BOOL", 0, "UPS.PowerSummary.PresentStatus.NeedReplacement", null, None, CommonLookups.ReplacebattInfo),
            new("BOOL", 0, "UPS.PowerSummary.PresentStatus.Overload", null, QuickPoll, CommonLookups.OverloadInfo),
            new("BOOL", 0, "UPS.PowerSummary.PresentStatus.OverTemperature", null, None, CommonLookups.OverheatInfo),
            new("BOOL", 0, "UPS.PowerSummary.PresentStatus.ShutdownImminent", null, None, CommonLookups.ShutdownimmInfo),
            new("BOOL", 0, "UPS.EVER1.EVER18.EVER19", null, None, CommonLookups.OverloadInfo),
            new("BOOL", 0, "UPS.EVER1.EVER18.EVER20", null, None, CommonLookups.LowbattInfo),
            new("BOOL", 0, "UPS.EVER1.EVER18.EVER21", null, None, CommonLookups.BoostInfo),
            new("BOOL", 0, "UPS.EVER1.EVER18.EVER22", null, None, CommonLookups.TrimInfo),
            new("BOOL", 0, "UPS.EVER1.EVER18.EVER25", null, None, CommonLookups.ChargingInfo),
            new("BOOL", 0, "UPS.EVER1.EVER18.EVER28", null, None, CommonLookups.ReplacebattInfo),
            new("BOOL", 0, "UPS.EVER1.EVER32.EVER33", null, None, CommonLookups.OverloadInfo),
            new("BOOL", 0, "UPS.EVER1.EVER32.EVER40", "%.0f", None, CommonLookups.CommfaultInfo),
            new("BOOL", 0, "UPS.EVER1.EVER97.EVER102", "%s", None, everOnOffInfo),
            new("experimental.status.workmode", 0, "UPS.EVER1.EVER97.EVER98", "%s", None, everWorkmode),
            new("experimental.status.messages", 0, "UPS.EVER1.EVER18.EVER28", null, None, everMessages),
            new("experimental.status.alarms", 0, "UPS.EVER1.EVER32.EVER33", null, None, everAlarms),
            new("load.off.delay", 0, "UPS.PowerSummary.DelayBeforeShutdown", "20", Cmd, null),
            new("shutdown.return", 0, "UPS.PowerSummary.DelayBeforeShutdown", "20", Cmd, null),
        ];
    }
}
