// Mapping tables ported from Network UPS Tools, drivers/mge-hid.c (MGE HID 1.61),
// GPL-2.0-or-later. Keep them in sync with that file rather than editing entries by hand.
using NutHub.Drivers.Hid.Descriptors;
using static NutHub.Drivers.Hid.UsbHid.HidMapFlags;

namespace NutHub.Drivers.Hid.UsbHid.Subdrivers;

internal sealed partial class MgeSubdriver
{
    /// <summary>The NUT subdriver this one is ported from, reported as driver.version.data.</summary>
    public override string Version => "MGE HID 1.61";

    /// <summary>Vendor-specific usage names (NUT mge_usage_lkp).</summary>
    private static readonly HidUsageTable VendorUsageTable = new(
    [
        ("Undefined", 0xffff0000),
        ("STS", 0xffff0001),
        ("Environment", 0xffff0002),
        ("Statistic", 0xffff0003),
        ("StatisticSystem", 0xffff0004),
        ("USB", 0xffff0005),
        ("Phase", 0xffff0010),
        ("PhaseID", 0xffff0011),
        ("Chopper", 0xffff0012),
        ("ChopperID", 0xffff0013),
        ("Inverter", 0xffff0014),
        ("InverterID", 0xffff0015),
        ("Rectifier", 0xffff0016),
        ("RectifierID", 0xffff0017),
        ("LCMSystem", 0xffff0018),
        ("LCMSystemID", 0xffff0019),
        ("LCMAlarm", 0xffff001a),
        ("LCMAlarmID", 0xffff001b),
        ("HistorySystem", 0xffff001c),
        ("HistorySystemID", 0xffff001d),
        ("Event", 0xffff001e),
        ("EventID", 0xffff001f),
        ("CircuitBreaker", 0xffff0020),
        ("TransferForbidden", 0xffff0021),
        ("OverallAlarm", 0xffff0022),
        ("Dephasing", 0xffff0023),
        ("BypassBreaker", 0xffff0024),
        ("PowerModule", 0xffff0025),
        ("PowerRate", 0xffff0026),
        ("PowerSource", 0xffff0027),
        ("CurrentPowerSource", 0xffff0028),
        ("RedundancyLevel", 0xffff0029),
        ("RedundancyLost", 0xffff002a),
        ("NotificationStatus", 0xffff002b),
        ("ProtectionLost", 0xffff002c),
        ("ConfigurationFailure", 0xffff002d),
        ("CompatibilityFailure", 0xffff002e),
        ("SwitchType", 0xffff0040),
        ("ConverterType", 0xffff0041),
        ("FrequencyConverterMode", 0xffff0042),
        ("AutomaticRestart", 0xffff0043),
        ("ForcedReboot", 0xffff0044),
        ("TestPeriod", 0xffff0045),
        ("EnergySaving", 0xffff0046),
        ("StartOnBattery", 0xffff0047),
        ("Schedule", 0xffff0048),
        ("DeepDischargeProtection", 0xffff0049),
        ("ShortCircuit", 0xffff004a),
        ("ExtendedVoltageMode", 0xffff004b),
        ("SensitivityMode", 0xffff004c),
        ("RemainingCapacityLimitSetting", 0xffff004d),
        ("ExtendedFrequencyMode", 0xffff004e),
        ("FrequencyConverterModeSetting", 0xffff004f),
        ("LowVoltageBoostTransfer", 0xffff0050),
        ("HighVoltageBoostTransfer", 0xffff0051),
        ("LowVoltageBuckTransfer", 0xffff0052),
        ("HighVoltageBuckTransfer", 0xffff0053),
        ("OverloadTransferEnable", 0xffff0054),
        ("OutOfToleranceTransferEnable", 0xffff0055),
        ("ForcedTransferEnable", 0xffff0056),
        ("LowVoltageBypassTransfer", 0xffff0057),
        ("HighVoltageBypassTransfer", 0xffff0058),
        ("FrequencyRangeBypassTransfer", 0xffff0059),
        ("LowVoltageEcoTransfer", 0xffff005a),
        ("HighVoltageEcoTransfer", 0xffff005b),
        ("FrequencyRangeEcoTransfer", 0xffff005c),
        ("ShutdownTimer", 0xffff005d),
        ("StartupTimer", 0xffff005e),
        ("RestartLevel", 0xffff005f),
        ("PhaseOutOfRange", 0xffff0060),
        ("CurrentLimitation", 0xffff0061),
        ("ThermalOverload", 0xffff0062),
        ("SynchroSource", 0xffff0063),
        ("FuseFault", 0xffff0064),
        ("ExternalProtectedTransfert", 0xffff0065),
        ("ExternalForcedTransfert", 0xffff0066),
        ("Compensation", 0xffff0067),
        ("EmergencyStop", 0xffff0068),
        ("PowerFactor", 0xffff0069),
        ("PeakFactor", 0xffff006a),
        ("ChargerType", 0xffff006b),
        ("HighPositiveDCBusVoltage", 0xffff006c),
        ("LowPositiveDCBusVoltage", 0xffff006d),
        ("HighNegativeDCBusVoltage", 0xffff006e),
        ("LowNegativeDCBusVoltage", 0xffff006f),
        ("FrequencyRangeTransfer", 0xffff0070),
        ("WiringFaultDetection", 0xffff0071),
        ("ControlStandby", 0xffff0072),
        ("ShortCircuitTolerance", 0xffff0073),
        ("VoltageTooHigh", 0xffff0074),
        ("VoltageTooLow", 0xffff0075),
        ("DCBusUnbalanced", 0xffff0076),
        ("FanFailure", 0xffff0077),
        ("WiringFault", 0xffff0078),
        ("Floating", 0xffff0079),
        ("OverCurrent", 0xffff007a),
        ("RemainingActivePower", 0xffff007b),
        ("Energy", 0xffff007c),
        ("Threshold", 0xffff007d),
        ("OverThreshold", 0xffff007e),
        ("Sensor", 0xffff0080),
        ("LowHumidity", 0xffff0081),
        ("HighHumidity", 0xffff0082),
        ("LowTemperature", 0xffff0083),
        ("HighTemperature", 0xffff0084),
        ("ECOControl", 0xffff0085),
        ("Efficiency", 0xffff0086),
        ("ABMEnable", 0xffff0087),
        ("NegativeCurrent", 0xffff0088),
        ("AutomaticStart", 0xffff0089),
        ("Count", 0xffff0090),
        ("Timer", 0xffff0091),
        ("Interval", 0xffff0092),
        ("TimerExpired", 0xffff0093),
        ("Mode", 0xffff0094),
        ("Country", 0xffff0095),
        ("State", 0xffff0096),
        ("Time", 0xffff0097),
        ("Code", 0xffff0098),
        ("DataValid", 0xffff0099),
        ("ToggleTimer", 0xffff009a),
        ("BypassTransferDelay", 0xffff009b),
        ("HysteresisVoltageTransfer", 0xffff009c),
        ("SlewRate", 0xffff009d),
        ("PDU", 0xffff00a0),
        ("Breaker", 0xffff00a1),
        ("BreakerID", 0xffff00a2),
        ("OverVoltage", 0xffff00a3),
        ("Tripped", 0xffff00a4),
        ("OverEnergy", 0xffff00a5),
        ("OverHumidity", 0xffff00a6),
        ("ConfigurationReset", 0xffff00a7),
        ("Level", 0xffff00a8),
        ("PDUType", 0xffff00a9),
        ("ReactivePower", 0xffff00aa),
        ("Pole", 0xffff00ab),
        ("PoleID", 0xffff00ac),
        ("Reset", 0xffff00ad),
        ("WatchdogReset", 0xffff00ae),
        ("iDesignator", 0xffff00ba),
        ("COPIBridge", 0xffff00e0),
        ("Gateway", 0xffff00e1),
        ("System", 0xffff00e5),
        ("Status", 0xffff00e9),
        ("iModel", 0xffff00f0),
        ("iVersion", 0xffff00f1),
        ("iTechnicalLevel", 0xffff00f2),
        ("iPartNumber", 0xffff00f3),
        ("iReferenceNumber", 0xffff00f4),
        ("iGang", 0xffff00f5),
    ]);

    /// <summary>The USB ids this subdriver supports (NUT mge_usb_device_table).</summary>
    private static readonly UsbDeviceId[] DeviceIds =
    [
        new(0x0463, 0x0001),
        new(0x0463, 0xffff),
        new(0x047c, 0xffff),
        new(0x0592, 0x0004),
        new(0x03f0, 0x1fe5),
        new(0x03f0, 0x1fe6),
        new(0x03f0, 0x1fe7),
        new(0x03f0, 0x1fe8),
        new(0x2b2d, 0xffff),
        new(0x06da, 0xffff),
        new(0x04b3, 0x0001),
        new(0x09d6, 0x0001),
    ];

    private static readonly NutLookup EatonChargerTypeInfo = NutLookup.Table([(0, "None"), (1, "Extended (CLA)"), (2, "Large extension"), (3, "Extra large extension (XL)"), (4, "ABM"), (5, "Constant Charge (CC)")]);

    private static readonly NutLookup EatonEnableDisableInfo = NutLookup.Table([(0, "disabled"), (1, "enabled")]);

    private static readonly NutLookup EatonInputBypassModeOffInfo = NutLookup.Table([(0, "disabled"), (1, "off")]);

    private static readonly NutLookup EatonOutletProtectionStatusInfo = NutLookup.Table([(0, "not powered"), (1, "not protected"), (2, "protected")]);

    private static readonly NutLookup MgeConfigFailure = NutLookup.Table([(1, "Fatal EEPROM fault!")]);

    private static readonly NutLookup MgeEmergencyStop = NutLookup.Table([(1, "Emergency stop!")]);

    private static readonly NutLookup MgeInverterVolthi = NutLookup.Table([(1, "Inverter AC voltage too high!")]);

    private static readonly NutLookup MgeInverterVoltlo = NutLookup.Table([(1, "Inverter AC voltage too low!")]);

    private static readonly NutLookup MgeOnbattInfo = NutLookup.Table([(1, "!online"), (0, "online")]);

    private static readonly NutLookup MgeSensitivityInfo = NutLookup.Table([(0, "normal"), (1, "high"), (2, "low")]);

    private static readonly NutLookup MgeShortCircuit = NutLookup.Table([(1, "Output short circuit!")]);

    private static readonly NutLookup MgeUpstypeConversion = NutLookup.Table([(1, "offline / line interactive"), (2, "online"), (3, "online - unitary/parallel"), (4, "online - parallel with hot standy"), (5, "online - hot standby redundancy")]);

    private static readonly NutLookup MgeWiringFault = NutLookup.Table([(1, "Wiring fault!")]);

    private static readonly NutLookup OutletEcoYesNoInfo = NutLookup.Table([(0, "The outlet is not ECO controlled"), (1, "The outlet is ECO controlled")]);

    /// <summary>Builds the HID to NUT mapping table; function lookups bind to this instance's state.</summary>
    private HidMapping[] BuildMappings()
    {
        NutLookup eatonAbmChrgDischrgInfo = NutLookup.Create([(1, "dummy")], EatonAbmChrgDischrgFun, null);
        NutLookup eatonAbmEnabledInfo = NutLookup.Create([(0, "dummy")], EatonAbmEnabledFun, null);
        NutLookup eatonAbmPathModeInfo = NutLookup.Create([(0, "dummy")], EatonAbmPathModeFun, null);
        NutLookup eatonAbmPathStatusInfo = NutLookup.Create([(0, "dummy")], EatonAbmPathStatusFun, null);
        NutLookup eatonAbmStatusInfo = NutLookup.Create([(1, "dummy")], EatonAbmStatusFun, null);
        NutLookup eatonChargingInfo = NutLookup.Create([(1, "dummy")], EatonAbmCheckChrgFun, null);
        NutLookup eatonCheckCountryInfo = NutLookup.Create([(0, "dummy")], EatonCheckCountryFun, null);
        NutLookup eatonComputeRealpowerInfo = NutLookup.Create([(0, "dummy")], EatonComputeRealpowerFun, null);
        NutLookup eatonConverterOnlineInfo = NutLookup.Create([(0, "dummy")], EatonConverterOnlineFun, null);
        NutLookup eatonDischargingInfo = NutLookup.Create([(1, "dummy")], EatonAbmCheckDischrgFun, null);
        NutLookup eatonInputBypassModeOnInfo = NutLookup.Create([(0, "disabled"), (1, "on")], EatonInputBypassCheckRange, null);
        NutLookup eatonInputEcoModeOnOffInfo = NutLookup.Create([(0, "dummy")], EatonInputBuzzwordmodeReport, EatonInputBuzzwordmodeSetvarNuf);
        NutLookup mgeBatteryCapacity = NutLookup.Create([], MgeBatteryCapacityFun, null);
        NutLookup mgeBatteryVoltage = NutLookup.Create([], MgeBatteryVoltageFun, null);
        NutLookup mgeBatteryVoltageNominal = NutLookup.Create([], MgeBatteryVoltageNominalFun, null);
        NutLookup mgeDateConversion = NutLookup.Create([], MgeDateConversionFun, MgeDateConversionNuf);
        NutLookup mgePowerfactorConversion = NutLookup.Create([], MgePowerfactorConversionFun, null);
        NutLookup mgeTimeConversion = NutLookup.Create([], MgeTimeConversionFun, MgeTimeConversionNuf);
        NutLookup nominalOutputVoltageInfo = NutLookup.Create([(200, "200"), (208, "208"), (220, "220"), (230, "230"), (240, "240"), (100, "100"), (110, "110"), (120, "120"), (127, "127")], NominalOutputVoltageFun, null);
        NutLookup pegasusThresholdInfo = NutLookup.Create([(10, "10"), (25, "25"), (60, "60")], EatonCheckPegasusFun, null);
        NutLookup pegasusYesNoInfo = NutLookup.Create([(0, "dummy")], PegasusYesNoInfoFun, PegasusYesNoInfoNuf);

        return
        [
            new("device.country", 20, "UPS.PowerSummary.Country", "Europe", Str | Static, eatonCheckCountryInfo),
            new("device.usb.version", 20, "UPS.System.USB.iVersion", null, Str | Static, CommonLookups.StringidConversion),
            new("battery.charge", 0, "UPS.PowerSummary.RemainingCapacity", "%.0f", None, null),
            new("battery.charge.low", 5, "UPS.PowerSummary.RemainingCapacityLimitSetting", "%.0f", Rw | Str | SemiStatic, null),
            new("battery.charge.low", 0, "UPS.PowerSummary.RemainingCapacityLimit", "%.0f", Static, null),
            new("battery.charge.restart", 3, "UPS.PowerSummary.RestartLevel", "%.0f", Rw | Str | SemiStatic, null),
            new("battery.capacity", 0, "UPS.BatterySystem.Battery.DesignCapacity", "%s", Static, mgeBatteryCapacity),
            new("battery.runtime", 0, "UPS.PowerSummary.RunTimeToEmpty", "%.0f", None, null),
            new("battery.runtime.low", 10, "UPS.PowerSummary.RemainingTimeLimit", "%.0f", Rw | Str, null),
            new("battery.runtime.elapsed", 0, "UPS.StatisticSystem.Input.[1].Statistic.[1].Time", "%.0f", QuickPoll, null),
            new("battery.runtime.low", 10, "UPS.PowerSummary.RemainingTimeLimit", "%.0f", Rw | Str, null),
            new("battery.temperature", 0, "UPS.BatterySystem.Battery.Temperature", "%s", None, CommonLookups.KelvinCelsiusConversion),
            new("battery.type", 0, "UPS.PowerSummary.iDeviceChemistry", "%s", Static, CommonLookups.StringidConversion),
            new("battery.voltage", 0, "UPS.BatterySystem.Voltage", "%.1f", None, null),
            new("battery.voltage", 0, "UPS.PowerSummary.Voltage", "%s", None, mgeBatteryVoltage),
            new("battery.voltage.nominal", 0, "UPS.BatterySystem.ConfigVoltage", "%.0f", Static, null),
            new("battery.voltage.nominal", 0, "UPS.PowerSummary.ConfigVoltage", "%s", Static, mgeBatteryVoltageNominal),
            new("battery.protection", 5, "UPS.BatterySystem.Battery.DeepDischargeProtection", "%s", Rw | Str | SemiStatic, CommonLookups.YesNoInfo),
            new("battery.energysave", 5, "UPS.PowerConverter.Input.[3].EnergySaving", "%s", Rw | Str | SemiStatic, CommonLookups.YesNoInfo),
            new("battery.energysave.load", 5, "UPS.PowerConverter.Input.[3].ConfigPercentLoad", "%.0f", Rw | Str | SemiStatic, null),
            new("battery.energysave.delay", 5, "UPS.PowerConverter.Input.[3].EnergySaving.ShutdownTimer", "%.0f", Rw | Str | SemiStatic, null),
            new("battery.energysave.delay", 5, "UPS.PowerConverter.Input.[3].ShutdownTimer", "%.0f", Rw | Str | SemiStatic, null),
            new("battery.energysave.realpower", 5, "UPS.PowerConverter.Input.[3].ConfigActivePower", "%.0f", Rw | Str | SemiStatic, null),
            new("battery.charger.abm.status", 0, "UPS.BatterySystem.Charger.ABMEnable", "%.0f", QuickPoll, eatonAbmEnabledInfo),
            new("battery.charger.mode.status", 0, "UPS.BatterySystem.Charger.Mode", "%.0f", QuickPoll, eatonAbmPathModeInfo),
            new("battery.charger.type.status", 0, "UPS.BatterySystem.Charger.Status", "%.0f", QuickPoll, eatonAbmPathStatusInfo),
            new("battery.charger.status", 0, "UPS.BatterySystem.Charger.Mode", "%.0f", QuickPoll, eatonAbmStatusInfo),
            new("battery.charger.status", 0, "UPS.BatterySystem.Charger.Status", "%.0f", QuickPoll, eatonAbmStatusInfo),
            new("battery.charger.type", 0, "UPS.BatterySystem.Charger.ChargerType", "%.0f", QuickPoll, EatonChargerTypeInfo),
            new("ups.efficiency", 0, "UPS.PowerConverter.Output.Efficiency", "%.0f", None, null),
            new("ups.firmware", 0, "UPS.PowerSummary.iVersion", "%s", Static, CommonLookups.StringidConversion),
            new("ups.load", 0, "UPS.PowerSummary.PercentLoad", "%.0f", None, null),
            new("ups.load.high", 5, "UPS.Flow.[4].ConfigPercentLoad", "%.0f", Rw | Str | SemiStatic, null),
            new("ups.delay.start", 10, "UPS.PowerSummary.DelayBeforeStartup", "30", Rw | Str | Absent, null),
            new("ups.delay.shutdown", 10, "UPS.PowerSummary.DelayBeforeShutdown", "20", Rw | Str | Absent, null),
            new("ups.timer.start", 0, "UPS.PowerSummary.DelayBeforeStartup", "%.0f", QuickPoll, null),
            new("ups.timer.shutdown", 0, "UPS.PowerSummary.DelayBeforeShutdown", "%.0f", QuickPoll, null),
            new("ups.timer.reboot", 0, "UPS.PowerSummary.DelayBeforeReboot", "%.0f", QuickPoll, null),
            new("ups.test.result", 0, "UPS.BatterySystem.Battery.Test", "%s", None, CommonLookups.TestReadInfo),
            new("ups.test.interval", 8, "UPS.BatterySystem.Battery.TestPeriod", "%.0f", Rw | Str | SemiStatic, null),
            new("ups.beeper.status", 0, "UPS.BatterySystem.Battery.AudibleAlarmControl", "%s", SemiStatic, CommonLookups.BeeperInfo),
            new("ups.beeper.status", 0, "UPS.PowerSummary.AudibleAlarmControl", "%s", SemiStatic, CommonLookups.BeeperInfo),
            new("ups.beeper.status", 0, "UPS.AudibleAlarmControl", "%s", SemiStatic, CommonLookups.BeeperInfo),
            new("ups.temperature", 0, "UPS.PowerSummary.Temperature", "%s", None, CommonLookups.KelvinCelsiusConversion),
            new("ups.power", 0, "UPS.PowerConverter.Output.ApparentPower", "%.0f", None, null),
            new("ups.L1.power", 0, "UPS.PowerConverter.Output.Phase.[1].ApparentPower", "%.0f", None, null),
            new("ups.L2.power", 0, "UPS.PowerConverter.Output.Phase.[2].ApparentPower", "%.0f", None, null),
            new("ups.L3.power", 0, "UPS.PowerConverter.Output.Phase.[3].ApparentPower", "%.0f", None, null),
            new("ups.power.nominal", 0, "UPS.Flow.[4].ConfigApparentPower", "%.0f", Static, null),
            new("ups.realpower", 0, "UPS.PowerConverter.Output.ActivePower", "%.0f", None, null),
            new("ups.realpower", 0, "UPS.Flow.[4].ConfigApparentPower", "-1", None, eatonComputeRealpowerInfo),
            new("ups.L1.realpower", 0, "UPS.PowerConverter.Output.Phase.[1].ActivePower", "%.0f", None, null),
            new("ups.L2.realpower", 0, "UPS.PowerConverter.Output.Phase.[2].ActivePower", "%.0f", None, null),
            new("ups.L3.realpower", 0, "UPS.PowerConverter.Output.Phase.[3].ActivePower", "%.0f", None, null),
            new("ups.realpower.nominal", 0, "UPS.Flow.[4].ConfigActivePower", "%.0f", Static, null),
            new("ups.start.auto", 5, "UPS.PowerConverter.Input.[1].AutomaticRestart", "%s", Rw | Str | SemiStatic, CommonLookups.YesNoInfo),
            new("ups.start.battery", 5, "UPS.PowerConverter.Input.[3].StartOnBattery", "%s", Rw | Str | SemiStatic, CommonLookups.YesNoInfo),
            new("ups.start.reboot", 5, "UPS.PowerConverter.Output.ForcedReboot", "%s", Rw | Str | SemiStatic, CommonLookups.YesNoInfo),
            new("ups.shutdown", 10, "UPS.PowerSummary.PresentStatus.Switchable", "%s", Rw | Str | SemiStatic | Enumerated, EatonEnableDisableInfo),
            new("ups.date", 10, "UPS.PowerSummary.Time", "%s", Rw | Str, mgeDateConversion),
            new("ups.time", 10, "UPS.PowerSummary.Time", "%s", Rw | Str, mgeTimeConversion),
            new("ups.type", 0, "UPS.PowerConverter.ConverterType", "%s", Static, MgeUpstypeConversion),
            new("BOOL", 0, "UPS.PowerSummary.PresentStatus.ACPresent", null, QuickPoll, CommonLookups.OnlineInfo),
            new("BOOL", 0, "UPS.PowerConverter.Input.[3].PresentStatus.Used", null, None, MgeOnbattInfo),
            new("BOOL", 0, "UPS.PowerSummary.PresentStatus.Discharging", null, QuickPoll, eatonDischargingInfo),
            new("BOOL", 0, "UPS.PowerSummary.PresentStatus.Charging", null, QuickPoll, eatonChargingInfo),
            new("BOOL", 0, "UPS.BatterySystem.Charger.Mode", "%.0f", QuickPoll, eatonAbmChrgDischrgInfo),
            new("BOOL", 0, "UPS.BatterySystem.Charger.Status", "%.0f", QuickPoll, eatonAbmChrgDischrgInfo),
            new("BOOL", 0, "UPS.PowerSummary.PresentStatus.BelowRemainingCapacityLimit", null, QuickPoll, CommonLookups.LowbattInfo),
            new("BOOL", 0, "UPS.PowerConverter.Output.Overload.[1].PresentStatus.OverThreshold", null, None, CommonLookups.OverloadInfo),
            new("BOOL", 0, "UPS.PowerConverter.Output.Overload.[2].PresentStatus.OverThreshold", null, None, CommonLookups.OverloadInfo),
            new("BOOL", 0, "UPS.PowerSummary.PresentStatus.Overload", null, None, CommonLookups.OverloadInfo),
            new("BOOL", 0, "UPS.PowerSummary.PresentStatus.NeedReplacement", null, None, CommonLookups.ReplacebattInfo),
            new("BOOL", 0, "UPS.LCMSystem.LCMAlarm.[2].PresentStatus.TimerExpired", null, None, CommonLookups.ReplacebattInfo),
            new("BOOL", 0, "UPS.PowerConverter.Input.[1].PresentStatus.Buck", null, None, CommonLookups.TrimInfo),
            new("BOOL", 0, "UPS.PowerConverter.Input.[1].PresentStatus.Boost", null, None, CommonLookups.BoostInfo),
            new("BOOL", 0, "UPS.PowerConverter.Input.[1].PresentStatus.VoltageOutOfRange", null, None, CommonLookups.VrangeInfo),
            new("BOOL", 0, "UPS.PowerConverter.Input.[1].PresentStatus.FrequencyOutOfRange", null, None, CommonLookups.FrangeInfo),
            new("BOOL", 0, "UPS.PowerSummary.PresentStatus.Good", null, None, CommonLookups.OffInfo),
            new("BOOL", 0, "UPS.PowerConverter.Input.[1].PresentStatus.Used", null, None, eatonConverterOnlineInfo),
            new("BOOL", 0, "UPS.PowerConverter.Input.[2].PresentStatus.Used", null, None, CommonLookups.BypassAutoInfo),
            new("BOOL", 0, "UPS.PowerConverter.Input.[4].PresentStatus.Used", null, None, CommonLookups.BypassManualInfo),
            new("BOOL", 0, "UPS.PowerConverter.Input.[5].PresentStatus.Used", null, None, CommonLookups.EcoModeInfo),
            new("BOOL", 0, "UPS.PowerSummary.PresentStatus.FanFailure", null, None, CommonLookups.FanfailInfo),
            new("BOOL", 0, "UPS.BatterySystem.Battery.PresentStatus.Present", null, None, CommonLookups.NobatteryInfo),
            new("BOOL", 0, "UPS.BatterySystem.Charger.PresentStatus.InternalFailure", null, None, CommonLookups.ChargerfailInfo),
            new("BOOL", 0, "UPS.BatterySystem.Charger.PresentStatus.VoltageTooHigh", null, None, CommonLookups.BattvolthiInfo),
            new("BOOL", 0, "UPS.PowerConverter.Input.[1].PresentStatus.VoltageTooHigh", null, None, CommonLookups.BattvolthiInfo),
            new("BOOL", 0, "UPS.BatterySystem.Battery.PresentStatus.VoltageTooHigh", null, None, CommonLookups.BattvolthiInfo),
            new("BOOL", 0, "UPS.BatterySystem.Charger.PresentStatus.VoltageTooLow", null, None, CommonLookups.BattvoltloInfo),
            new("BOOL", 0, "UPS.PowerConverter.Input.[1].PresentStatus.VoltageTooLow", null, None, MgeOnbattInfo),
            new("BOOL", 0, "UPS.PowerSummary.PresentStatus.InternalFailure", null, None, CommonLookups.CommfaultInfo),
            new("BOOL", 0, "UPS.PowerSummary.PresentStatus.OverTemperature", null, None, CommonLookups.OverheatInfo),
            new("BOOL", 0, "UPS.PowerSummary.PresentStatus.ShutdownImminent", null, None, CommonLookups.ShutdownimmInfo),
            new("ups.alarm", 0, "UPS.PowerSummary.PresentStatus.EmergencyStop", null, None, MgeEmergencyStop),
            new("ups.alarm", 0, "UPS.PowerConverter.Input.[1].PresentStatus.WiringFault", null, None, MgeWiringFault),
            new("ups.alarm", 0, "UPS.PowerSummary.PresentStatus.ConfigurationFailure", null, None, MgeConfigFailure),
            new("ups.alarm", 0, "UPS.PowerConverter.Inverter.PresentStatus.VoltageTooHigh", null, None, MgeInverterVolthi),
            new("ups.alarm", 0, "UPS.PowerConverter.Inverter.PresentStatus.VoltageTooLow", null, None, MgeInverterVoltlo),
            new("ups.alarm", 0, "UPS.PowerConverter.Output.PresentStatus.ShortCircuit", null, None, MgeShortCircuit),
            new("input.voltage", 0, "UPS.PowerConverter.Input.[1].Voltage", "%.1f", None, null),
            new("input.L1-N.voltage", 0, "UPS.PowerConverter.Input.[1].Phase.[1].Voltage", "%.1f", None, null),
            new("input.L2-N.voltage", 0, "UPS.PowerConverter.Input.[1].Phase.[2].Voltage", "%.1f", None, null),
            new("input.L3-N.voltage", 0, "UPS.PowerConverter.Input.[1].Phase.[3].Voltage", "%.1f", None, null),
            new("input.L1-L2.voltage", 0, "UPS.PowerConverter.Input.[1].Phase.[12].Voltage", "%.1f", None, null),
            new("input.L2-L3.voltage", 0, "UPS.PowerConverter.Input.[1].Phase.[23].Voltage", "%.1f", None, null),
            new("input.L3-L1.voltage", 0, "UPS.PowerConverter.Input.[1].Phase.[31].Voltage", "%.1f", None, null),
            new("input.voltage.nominal", 0, "UPS.Flow.[1].ConfigVoltage", "%.0f", Static, null),
            new("input.current", 0, "UPS.PowerConverter.Input.[1].Current", "%.2f", None, null),
            new("input.L1.current", 0, "UPS.PowerConverter.Input.[1].Phase.[1].Current", "%.1f", None, null),
            new("input.L2.current", 0, "UPS.PowerConverter.Input.[1].Phase.[2].Current", "%.1f", None, null),
            new("input.L3.current", 0, "UPS.PowerConverter.Input.[1].Phase.[3].Current", "%.1f", None, null),
            new("input.current.nominal", 0, "UPS.Flow.[1].ConfigCurrent", "%.2f", Static, null),
            new("input.frequency", 0, "UPS.PowerConverter.Input.[1].Frequency", "%.1f", None, null),
            new("input.frequency.nominal", 0, "UPS.Flow.[1].ConfigFrequency", "%.0f", Static, null),
            new("input.transfer.low", 5, "UPS.PowerConverter.Output.LowVoltageTransfer", "%.0f", Rw | Str | SemiStatic, null),
            new("input.transfer.eco.low", 5, "UPS.PowerConverter.Output.LowVoltageEcoTransfer", "%.0f", Rw | Str | SemiStatic, null),
            new("input.transfer.bypass.low", 5, "UPS.PowerConverter.Output.LowVoltageBypassTransfer", "%.0f", Rw | Str | SemiStatic, null),
            new("input.transfer.boost.low", 5, "UPS.PowerConverter.Output.LowVoltageBoostTransfer", "%.0f", Rw | Str | SemiStatic, null),
            new("input.transfer.boost.high", 5, "UPS.PowerConverter.Output.HighVoltageBoostTransfer", "%.0f", Rw | Str | SemiStatic, null),
            new("input.transfer.trim.low", 5, "UPS.PowerConverter.Output.LowVoltageBuckTransfer", "%.0f", Rw | Str | SemiStatic, null),
            new("input.transfer.high", 5, "UPS.PowerConverter.Output.HighVoltageTransfer", "%.0f", Rw | Str | SemiStatic, null),
            new("input.transfer.eco.high", 5, "UPS.PowerConverter.Output.HighVoltageEcoTransfer", "%.0f", Rw | Str | SemiStatic, null),
            new("input.transfer.bypass.high", 5, "UPS.PowerConverter.Output.HighVoltageBypassTransfer", "%.0f", Rw | Str | SemiStatic, null),
            new("input.transfer.frequency.bypass.range", 5, "UPS.PowerConverter.Output.FrequencyRangeBypassTransfer", "%.0f", Rw | Str | SemiStatic, null),
            new("input.transfer.frequency.eco.range", 5, "UPS.PowerConverter.Output.FrequencyRangeEcoTransfer", "%.0f", Rw | Str | SemiStatic, null),
            new("input.transfer.hysteresis", 5, "UPS.PowerConverter.Output.HysteresisVoltageTransfer", "%.0f", Rw | Str | SemiStatic, null),
            new("input.transfer.bypass.forced", 8, "UPS.PowerConverter.Input.[2].ForcedTransferEnable", "%.0f", Rw | Str | SemiStatic, EatonEnableDisableInfo),
            new("input.transfer.bypass.overload", 8, "UPS.PowerConverter.Input.[2].OverloadTransferEnable", "%.0f", Rw | Str | SemiStatic, EatonEnableDisableInfo),
            new("input.transfer.bypass.outlimits", 8, "UPS.PowerConverter.Input.[2].OutOfToleranceTransferEnable", "%.0f", Rw | Str | SemiStatic, EatonEnableDisableInfo),
            new("input.transfer.trim.high", 5, "UPS.PowerConverter.Output.HighVoltageBuckTransfer", "%.0f", Rw | Str | SemiStatic, null),
            new("input.sensitivity", 10, "UPS.PowerConverter.Output.SensitivityMode", "%s", Rw | Str | SemiStatic, MgeSensitivityInfo),
            new("input.voltage.extended", 5, "UPS.PowerConverter.Output.ExtendedVoltageMode", "%s", Rw | Str | SemiStatic, CommonLookups.YesNoInfo),
            new("input.frequency.extended", 5, "UPS.PowerConverter.Output.ExtendedFrequencyMode", "%s", Rw | Str | SemiStatic, CommonLookups.YesNoInfo),
            new("input.bypass.voltage", 0, "UPS.PowerConverter.Input.[2].Voltage", "%.1f", QuickPoll, null),
            new("input.bypass.L1-N.voltage", 0, "UPS.PowerConverter.Input.[2].Phase.[1].Voltage", "%.1f", None, null),
            new("input.bypass.L2-N.voltage", 0, "UPS.PowerConverter.Input.[2].Phase.[2].Voltage", "%.1f", None, null),
            new("input.bypass.L3-N.voltage", 0, "UPS.PowerConverter.Input.[2].Phase.[3].Voltage", "%.1f", None, null),
            new("input.bypass.L1-L2.voltage", 0, "UPS.PowerConverter.Input.[2].Phase.[12].Voltage", "%.1f", None, null),
            new("input.bypass.L2-L3.voltage", 0, "UPS.PowerConverter.Input.[2].Phase.[23].Voltage", "%.1f", None, null),
            new("input.bypass.L3-L1.voltage", 0, "UPS.PowerConverter.Input.[2].Phase.[31].Voltage", "%.1f", None, null),
            new("input.bypass.voltage.nominal", 0, "UPS.Flow.[2].ConfigVoltage", "%.0f", Static, null),
            new("input.bypass.current", 0, "UPS.PowerConverter.Input.[2].Current", "%.2f", None, null),
            new("input.bypass.L1.current", 0, "UPS.PowerConverter.Input.[2].Phase.[1].Current", "%.1f", None, null),
            new("input.bypass.L2.current", 0, "UPS.PowerConverter.Input.[2].Phase.[2].Current", "%.1f", None, null),
            new("input.bypass.L3.current", 0, "UPS.PowerConverter.Input.[2].Phase.[3].Current", "%.1f", None, null),
            new("input.bypass.current.nominal", 0, "UPS.Flow.[2].ConfigCurrent", "%.2f", Static, null),
            new("input.bypass.frequency", 0, "UPS.PowerConverter.Input.[2].Frequency", "%.1f", QuickPoll, null),
            new("input.bypass.frequency.nominal", 0, "UPS.Flow.[2].ConfigFrequency", "%.0f", Static, null),
            new("input.bypass.switch.on", 8, "UPS.PowerConverter.Input.[2].SwitchOnControl", "%.0f", Rw | Str | QuickPoll, eatonInputBypassModeOnInfo),
            new("input.bypass.switch.off", 12, "UPS.PowerConverter.Input.[2].SwitchOffControl", "%.0f", Rw | Str | QuickPoll, EatonInputBypassModeOffInfo),
            new("input.bypass.switchable", 8, "UPS.PowerConverter.Input.[2].Switchable", "%.0f", Rw | Str | SemiStatic, EatonEnableDisableInfo),
            new("output.voltage", 0, "UPS.PowerConverter.Output.Voltage", "%.1f", None, null),
            new("output.L1-N.voltage", 0, "UPS.PowerConverter.Output.Phase.[1].Voltage", "%.1f", None, null),
            new("output.L2-N.voltage", 0, "UPS.PowerConverter.Output.Phase.[2].Voltage", "%.1f", None, null),
            new("output.L3-N.voltage", 0, "UPS.PowerConverter.Output.Phase.[3].Voltage", "%.1f", None, null),
            new("output.L1-L2.voltage", 0, "UPS.PowerConverter.Output.Phase.[12].Voltage", "%.1f", None, null),
            new("output.L2-L3.voltage", 0, "UPS.PowerConverter.Output.Phase.[23].Voltage", "%.1f", None, null),
            new("output.L3-L1.voltage", 0, "UPS.PowerConverter.Output.Phase.[31].Voltage", "%.1f", None, null),
            new("output.voltage.nominal", 3, "UPS.Flow.[4].ConfigVoltage", "%.0f", Rw | Str | SemiStatic | Enumerated, nominalOutputVoltageInfo),
            new("output.current", 0, "UPS.PowerConverter.Output.Current", "%.2f", None, null),
            new("output.L1.current", 0, "UPS.PowerConverter.Output.Phase.[1].Current", "%.1f", None, null),
            new("output.L2.current", 0, "UPS.PowerConverter.Output.Phase.[2].Current", "%.1f", None, null),
            new("output.L3.current", 0, "UPS.PowerConverter.Output.Phase.[3].Current", "%.1f", None, null),
            new("output.current.nominal", 0, "UPS.Flow.[4].ConfigCurrent", "%.2f", None, null),
            new("output.frequency", 0, "UPS.PowerConverter.Output.Frequency", "%.1f", None, null),
            new("output.frequency.nominal", 0, "UPS.Flow.[4].ConfigFrequency", "%.0f", Static, null),
            new("output.powerfactor", 0, "UPS.PowerConverter.Output.PowerFactor", "%s", None, mgePowerfactorConversion),
            new("outlet.id", 0, "UPS.OutletSystem.Outlet.[1].OutletID", "%.0f", Static, null),
            new("outlet.desc", 20, "UPS.OutletSystem.Outlet.[1].OutletID", "Main Outlet", Rw | Str | Absent, null),
            new("outlet.switchable", 0, "UPS.OutletSystem.Outlet.[1].PresentStatus.Switchable", "%s", Static, CommonLookups.YesNoInfo),
            new("outlet.power", 6, "UPS.OutletSystem.Outlet.[1].ConfigApparentPower", "%s", Rw | Str | SemiStatic | Enumerated, pegasusThresholdInfo),
            new("outlet.power", 0, "UPS.OutletSystem.Outlet.[1].ApparentPower", "%.0f", None, null),
            new("outlet.realpower", 0, "UPS.OutletSystem.Outlet.[1].ActivePower", "%.0f", None, null),
            new("outlet.current", 0, "UPS.OutletSystem.Outlet.[1].Current", "%.2f", None, null),
            new("outlet.powerfactor", 0, "UPS.OutletSystem.Outlet.[1].PowerFactor", "%.2f", None, null),
            new("outlet.1.id", 0, "UPS.OutletSystem.Outlet.[2].OutletID", "%.0f", Static, null),
            new("outlet.1.desc", 20, "UPS.OutletSystem.Outlet.[2].OutletID", "PowerShare Outlet 1", Rw | Str | Absent, null),
            new("outlet.1.switchable", 0, "UPS.OutletSystem.Outlet.[2].PresentStatus.Switchable", "%s", Static, CommonLookups.YesNoInfo),
            new("outlet.1.status", 0, "UPS.OutletSystem.Outlet.[2].PresentStatus.SwitchOn/Off", "%s", None, CommonLookups.OnOffInfo),
            new("outlet.1.protect.status", 0, "UPS.OutletSystem.Outlet.[2].Status", "%s", None, EatonOutletProtectionStatusInfo),
            new("outlet.1.designator", 0, "UPS.OutletSystem.Outlet.[2].iDesignator", null, Static, CommonLookups.StringidConversion),
            new("outlet.1.status", 0, "UPS.PowerSummary.PresentStatus.ACPresent", "%s", None, CommonLookups.OnOffInfo),
            new("outlet.1.autoswitch.charge.low", 3, "UPS.OutletSystem.Outlet.[2].RemainingCapacityLimit", "%.0f", Rw | Str | SemiStatic, null),
            new("outlet.1.delay.shutdown", 5, "UPS.OutletSystem.Outlet.[2].ShutdownTimer", "%.0f", Rw | Str | SemiStatic, null),
            new("outlet.1.delay.start", 5, "UPS.OutletSystem.Outlet.[2].StartupTimer", "%.0f", Rw | Str | SemiStatic, null),
            new("outlet.1.power", 0, "UPS.OutletSystem.Outlet.[2].ApparentPower", "%.0f", None, null),
            new("outlet.1.realpower", 0, "UPS.OutletSystem.Outlet.[2].ActivePower", "%.0f", None, null),
            new("outlet.1.current", 0, "UPS.OutletSystem.Outlet.[2].Current", "%.2f", None, null),
            new("outlet.1.powerfactor", 0, "UPS.OutletSystem.Outlet.[2].PowerFactor", "%.2f", None, null),
            new("outlet.1.ecocontrol", 0, "UPS.OutletSystem.Outlet.[2].ECOControl", "%s", SemiStatic, OutletEcoYesNoInfo),
            new("outlet.2.id", 0, "UPS.OutletSystem.Outlet.[3].OutletID", "%.0f", Static, null),
            new("outlet.2.desc", 20, "UPS.OutletSystem.Outlet.[3].OutletID", "PowerShare Outlet 2", Rw | Str | Absent, null),
            new("outlet.2.switchable", 3, "UPS.OutletSystem.Outlet.[3].PresentStatus.Switchable", "%s", Rw | Str | SemiStatic, pegasusYesNoInfo),
            new("outlet.2.switchable", 0, "UPS.OutletSystem.Outlet.[3].PresentStatus.Switchable", "%s", None, CommonLookups.YesNoInfo),
            new("outlet.2.status", 0, "UPS.OutletSystem.Outlet.[3].PresentStatus.SwitchOn/Off", "%s", None, CommonLookups.OnOffInfo),
            new("outlet.2.protect.status", 0, "UPS.OutletSystem.Outlet.[3].Status", "%s", None, EatonOutletProtectionStatusInfo),
            new("outlet.2.autoswitch.charge.low", 3, "UPS.OutletSystem.Outlet.[3].RemainingCapacityLimit", "%.0f", Rw | Str | SemiStatic, null),
            new("outlet.2.delay.shutdown", 5, "UPS.OutletSystem.Outlet.[3].ShutdownTimer", "%.0f", Rw | Str | SemiStatic, null),
            new("outlet.2.delay.start", 5, "UPS.OutletSystem.Outlet.[3].StartupTimer", "%.0f", Rw | Str | SemiStatic, null),
            new("outlet.2.power", 0, "UPS.OutletSystem.Outlet.[3].ApparentPower", "%.0f", None, null),
            new("outlet.2.realpower", 0, "UPS.OutletSystem.Outlet.[3].ActivePower", "%.0f", None, null),
            new("outlet.2.current", 0, "UPS.OutletSystem.Outlet.[3].Current", "%.2f", None, null),
            new("outlet.2.powerfactor", 0, "UPS.OutletSystem.Outlet.[3].PowerFactor", "%.2f", None, null),
            new("outlet.2.ecocontrol", 0, "UPS.OutletSystem.Outlet.[3].ECOControl", "%s", SemiStatic, OutletEcoYesNoInfo),
            new("outlet.3.id", 0, "UPS.OutletSystem.Outlet.[4].OutletID", "%.0f", Static, null),
            new("outlet.3.desc", 20, "UPS.OutletSystem.Outlet.[4].OutletID", "PowerShare Outlet 2", Rw | Str | Absent, null),
            new("outlet.3.switchable", 3, "UPS.OutletSystem.Outlet.[4].PresentStatus.Switchable", "%s", Rw | Str | SemiStatic, pegasusYesNoInfo),
            new("outlet.3.switchable", 0, "UPS.OutletSystem.Outlet.[4].PresentStatus.Switchable", "%s", None, CommonLookups.YesNoInfo),
            new("outlet.3.status", 0, "UPS.OutletSystem.Outlet.[4].PresentStatus.SwitchOn/Off", "%s", None, CommonLookups.OnOffInfo),
            new("outlet.3.protect.status", 0, "UPS.OutletSystem.Outlet.[4].Status", "%s", None, EatonOutletProtectionStatusInfo),
            new("outlet.3.autoswitch.charge.low", 3, "UPS.OutletSystem.Outlet.[4].RemainingCapacityLimit", "%.0f", Rw | Str | SemiStatic, null),
            new("outlet.3.delay.shutdown", 5, "UPS.OutletSystem.Outlet.[4].ShutdownTimer", "%.0f", Rw | Str | SemiStatic, null),
            new("outlet.3.delay.start", 5, "UPS.OutletSystem.Outlet.[4].StartupTimer", "%.0f", Rw | Str | SemiStatic, null),
            new("outlet.3.power", 0, "UPS.OutletSystem.Outlet.[4].ApparentPower", "%.0f", None, null),
            new("outlet.3.realpower", 0, "UPS.OutletSystem.Outlet.[4].ActivePower", "%.0f", None, null),
            new("outlet.3.current", 0, "UPS.OutletSystem.Outlet.[4].Current", "%.2f", None, null),
            new("outlet.3.powerfactor", 0, "UPS.OutletSystem.Outlet.[4].PowerFactor", "%.2f", None, null),
            new("outlet.3.ecocontrol", 0, "UPS.OutletSystem.Outlet.[4].ECOControl", "%s", SemiStatic, OutletEcoYesNoInfo),
            new("test.battery.start.quick", 0, "UPS.BatterySystem.Battery.Test", "1", Cmd, null),
            new("test.battery.start.deep", 0, "UPS.BatterySystem.Battery.Test", "2", Cmd, null),
            new("test.battery.stop", 0, "UPS.BatterySystem.Battery.Test", "3", Cmd, null),
            new("load.off.delay", 0, "UPS.PowerSummary.DelayBeforeShutdown", "20", Cmd, null),
            new("load.on.delay", 0, "UPS.PowerSummary.DelayBeforeStartup", "30", Cmd, null),
            new("shutdown.stop", 0, "UPS.PowerSummary.DelayBeforeShutdown", "-1", Cmd, null),
            new("shutdown.reboot", 0, "UPS.PowerSummary.DelayBeforeReboot", "10", Cmd, null),
            new("beeper.off", 0, "UPS.PowerSummary.AudibleAlarmControl", "1", Cmd, null),
            new("beeper.on", 0, "UPS.PowerSummary.AudibleAlarmControl", "2", Cmd, null),
            new("beeper.mute", 0, "UPS.BatterySystem.Battery.AudibleAlarmControl", "3", Cmd, null),
            new("beeper.mute", 0, "UPS.PowerSummary.AudibleAlarmControl", "3", Cmd, null),
            new("beeper.disable", 0, "UPS.BatterySystem.Battery.AudibleAlarmControl", "1", Cmd, null),
            new("beeper.disable", 0, "UPS.PowerSummary.AudibleAlarmControl", "1", Cmd, null),
            new("beeper.enable", 0, "UPS.BatterySystem.Battery.AudibleAlarmControl", "2", Cmd, null),
            new("beeper.enable", 0, "UPS.PowerSummary.AudibleAlarmControl", "2", Cmd, null),
            new("beeper.disable", 0, "UPS.AudibleAlarmControl", "1", Cmd, null),
            new("beeper.enable", 0, "UPS.AudibleAlarmControl", "2", Cmd, null),
            new("outlet.1.load.off", 0, "UPS.OutletSystem.Outlet.[2].DelayBeforeShutdown", "0", Cmd, null),
            new("outlet.1.load.on", 0, "UPS.OutletSystem.Outlet.[2].DelayBeforeStartup", "0", Cmd, null),
            new("outlet.2.load.off", 0, "UPS.OutletSystem.Outlet.[3].DelayBeforeShutdown", "0", Cmd, null),
            new("outlet.2.load.on", 0, "UPS.OutletSystem.Outlet.[3].DelayBeforeStartup", "0", Cmd, null),
            new("outlet.3.load.off", 0, "UPS.OutletSystem.Outlet.[4].DelayBeforeShutdown", "0", Cmd, null),
            new("outlet.3.load.on", 0, "UPS.OutletSystem.Outlet.[4].DelayBeforeStartup", "0", Cmd, null),
            new("experimental.ecomode.stop", 0, "UPS.PowerConverter.Input.[5].Switchable", "0", Cmd, null),
            new("experimental.ecomode.start", 0, "UPS.PowerConverter.Input.[5].Switchable", "1", Cmd, null),
            new("experimental.essmode.start", 0, "UPS.PowerConverter.Input.[5].Switchable", "2", Cmd, null),
            new("experimental.essmode.stop", 0, "UPS.PowerConverter.Input.[5].Switchable", "0", Cmd, null),
            new("bypass.start", 0, "UPS.PowerConverter.Input.[2].SwitchOnControl", "1", Cmd, null),
            new("bypass.stop", 0, "UPS.PowerConverter.Input.[2].SwitchOffControl", "1", Cmd, null),
            new("input.eco.switchable", 8, "UPS.PowerConverter.Input.[5].Switchable", "%.0f", Rw | Str | QuickPoll, eatonInputEcoModeOnOffInfo),
        ];
    }
}
